### PR TITLE
EnTT 2.7.3 Upgrade

### PR DESCRIPTION
**Pull request by john4744**
Issue: https://devtopia.esri.com/runtime/home-one/issues/54
Upgrading from EnTT 2.7.2 -> 2.7.3
Now that we use clang on Android, I'm also reverting our compiler fixes that were in place.
3rdParty vTest: http://runtime-test.esri.com:8080/job/3rdparty_vtest_interface/276/downstreambuildview/
RuntimeCore vTest: http://runtime-test.esri.com:8080/job/vtest_interface/1635/downstreambuildview/

cc @irmackenzie

### CODE REVIEW

**Review by chri7325 — APPROVED** [review]
Looks good! @crezefire sorry if I've already asked this but looking at https://github.com/Esri/entt/compare/master...Esri:john4744/runtimecore, do you think it would be worth trying to upstream the last bit so we can be fully in sync with master going forward?

**Comment by vimmy-io** [comment]
Might be worth trying to raise an issue, although it is exposing internal functionality which is not always ideal....

**Review by dkalowsk — APPROVED** [review]

**Comment by skypjack** [comment]
I agree, exposing internal functionalities isn't always ideal. :-)  
That said, I'm be glad to know Esri is using `EnTT`!! I'd be even more glad to mention it in the wiki if possible.  
Would you like to open a PR for that instead? :wink:

**Comment by chri7325** [comment]
@skypjack of course! Where should we open a PR to add our name to the list?

**Comment by skypjack** [comment]
Hi @chri7325 Thank you for your answer!

You can either open an issue or a PR for the file `links.md` [here](https://github.com/skypjack/entt).  
Actually an issue is just fine. All what is needed is a brief description and the links you want to see listed among the others.  

Usually I put a line in the file mentioned above for the companies that I know are using `EnTT` but that (let me say) never _said it publicly_.
Esri is one of these but of course I would be **really** happy to have you open an issue for that!!

**Comment by chri7325** [comment]
@skypjack sounds good!  I created an issue in the parent repo https://github.com/skypjack/entt/issues/242.  Please let me know if you need anything else.

**Comment by skypjack** [comment]
@chri7325 Thank you very much!! Really, really, **really** appreciated.  
I hope you enjoyed  EnTT so far and feel free to ping me whenever you need.  
I'll edit the links as soon as possible (most likely tomorrow, it's half past midnight here).

**Pull request merged**
