### PR TITLE
Update to v3.2.0

### PR DESCRIPTION
**Pull request by irmackenzie**
For issue:
https://devtopia.esri.com/runtime/millennium-falcon/issues/96

* Branched runtimecore.
* Merged commit 03c3ee514b6160c41579edb2f334d7d6f54cf664 (tagged 3.2.0)
* Manually edited registry.hpp to re-add the one modification made to entt in runtimecore, which got lost in the merge process.

### CODE REVIEW

**Comment by irmackenzie** [comment]
Comparison of this branch with the version of entt that we are updating to (3.2.0):

https://github.com/Esri/entt/compare/03c3ee514b6160c41579edb2f334d7d6f54cf664...Esri:inne0000/runtimecore_update_to_320

**Comment by irmackenzie** [comment]
Test build of RTC updated to use this:
http://runtime-test.esri.com:8080/job/vtest-runtimecore-interface/7901/downstreambuildview/

**Review by chri7325 — APPROVED** [review]
Looks good!

**Comment by garythomson** [comment]
This PR was superseded.

**Pull request closed without merging**
